{
  "comments": [
    {
      "key": {
        "uuid": "dbe33f79_d002041e",
        "filename": "include/error_monitors/smi_monitor.hpp",
        "patchSetId": 7
      },
      "lineNbr": 2,
      "author": {
        "id": 1000168
      },
      "writtenOn": "2021-02-12T15:25:58Z",
      "side": 1,
      "message": "nit: 2021",
      "range": {
        "startLine": 2,
        "startChar": 17,
        "endLine": 2,
        "endChar": 22
      },
      "revId": "62dff99a52fd18622f6e615e47bc711373e0b704",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "90e66e9f_adee4328",
        "filename": "include/error_monitors/smi_monitor.hpp",
        "patchSetId": 7
      },
      "lineNbr": 29,
      "author": {
        "id": 1000168
      },
      "writtenOn": "2021-02-12T15:25:58Z",
      "side": 1,
      "message": "Where is this instantiated. I am unable to see from where the instance of this is created to get it started. Actually, i see the same till the final patch. Not sure, whether i missed some patch. Please clarify.",
      "revId": "62dff99a52fd18622f6e615e47bc711373e0b704",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}